### PR TITLE
#912 feature gate for apt install test

### LINKED ISSUE #912: Add feature gate for apt install local file rust integration test
**Describe the bug**
At the moment `cargo test` fails **locally** when the [sudo runner is not enabled in `~/.cargo/config`](https://github.com/rust-lang/cargo/issues/5999). This happens because the test installs rolldice which requires sudo.   

This test is more of an integration test than a unit test and should be feature gated such that they only run in a dedicated pipeline.

```shell
failures:
    install_from_local_file_success::path
    install_from_local_file_success::path_with_version
    install_from_local_file_success::version_with_path

```
AC: 
- feature gate

### PR DESCRIPTION
**Pull request by initard**
## Proposed changes
Closes #912, #930  
- added new "requires-sudo" feature gate

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
#912 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: plugins/tedge_apt_plugin/tests/main.rs [hunk 1]
```diff
@@ -1,163 +1,172 @@
...
 )]
-#[serial]
-#[test_case(
+    #[serial]
+    #[test_case(
     &format!("install {} --module-version {} --file {}", PACKAGE_NAME,  PACKAGE_VERSION, PACKAGE_FILE_PATH),
     PACKAGE_NAME,
     0
     ; "version with path"
 )]
```
Comment (matthiasbeyer) [inline plugins/tedge_apt_plugin/tests/main.rs:150]: shouldn't this be indented as well (same for the above instances of `test_case()`)?

File: plugins/tedge_apt_plugin/tests/main.rs [hunk 2]
```diff
@@ -1,163 +1,172 @@
...
-// expected stderr
-//
-// expected exit code
-//
-// description about the test
-#[test_case(
+#[cfg(feature = "integration-test")]
+mod tests {
+    use hamcrest2::prelude::*;
+    #[allow(unused_imports)]
```
Comment (albinsuresh) [inline plugins/tedge_apt_plugin/tests/main.rs:4]: Instead of marking these as dead code, I believe you can mask these using the same `requires-sudo` feature gate that the test using this constant is gated with. Same for the `dead_code` annotations used below.

**Comment by initard** [comment]
Thanks for the feedback, I pushed both suggestions :+1:

**Review by albinsuresh — APPROVED** [review]
