### PR TITLE
#937 fixing sm plugins path error message

### LINKED ISSUE #937: SmAgentConfig ignores --config-dir
**Describe the bug**
The tedge-agent does not seach sm-plugins in config dir. (see [code](https://github.com/thin-edge/thin-edge.io/blob/5b918722498871637163d32aa4d4aaa2808394e8/crates/core/tedge_agent/src/agent.rs#L77))

**To Reproduce**
Shift sm-plugins somewhere else than /etc/sm-plugins.

**Expected behavior**
Error: Couldn't load plugins from /etc/tedge/sm-plugins ➡️ Load plugins from $CONFIG_DIR/sm-plugins 

**Screenshots**
-

**Environment (please complete the following information):**
thin-edge version: 5b918722

**Additional context**

### PR DESCRIPTION
**Pull request by initard**
Signed-off-by: initard <solo@softwareag.com>

## Proposed changes
- Closes #937

Fixing error message when the `sm-plugins` directory exists **but** it is empty. 

```shell
# you can test by making sm-plugins in /tmp
mkdir /tmp/sm-plugins
# run tedge_agent with --config-dir
./target/debug/tedge_agent --config-dir /tmp
```

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
- #937 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: crates/core/tedge_agent/src/agent.rs [hunk 1]
```diff
@@ -198,16 +200,16 @@ impl SmAgent {
         info!("Starting tedge agent");
 
         let mut mqtt = Connection::new(&self.config.mqtt_config).await?;
+        let plugins_path = self.config.sm_home.join(SM_PLUGINS);
```
Comment (PradeepKiruvale) [inline crates/core/tedge_agent/src/agent.rs:203]: Would be better if we rename `plugins_path` to `sm_plugins_path`. Since there could be other plugins as well right?

**Review by PradeepKiruvale — APPROVED** [review]
Added one minor comment.

File: crates/core/tedge_agent/src/agent.rs (hunk 1 above)
Comment (initard) [reply crates/core/tedge_agent/src/agent.rs]: sure

**Comment by initard** [comment]
@didier-wenzek, @makr11st, currently when the sm-plugins directory is empty we `return Err(AgentError::NoPlugins);`

The issue is that returning an error will terminate the agent process. 

> Is it better to not return an error but simply display a `warn!` message?

**Comment by didier-wenzek** [comment]
> @didier-wenzek, @makr11st, currently when the sm-plugins directory is empty we `return Err(AgentError::NoPlugins);`
> 
> The issue is that returning an error will terminate the agent process.
> 
> > Is it better to not return an error but simply display a `warn!` message?

This is not an error to have no plugins for software management (either because, the user is just starting to use thin-edge or because he is not interested by the sm feature). Hence, the agent must not stop and just issue a warning.

**Review by rina23q — APPROVED** [review]
