### PR TITLE
Closes #1040 use config-dir feature for initalize and run

### LINKED ISSUE #1040: tedge_mapper (partially) ignores --config-dir
**Describe the bug**
Without `/etc/tedge/operations/c8y`, `tedge_mapper` fails to start even though `--config-dir` tells it to look elsewhere

**To Reproduce**
- move `/etc/tedge` somewhere else (on my device, `/mnt/data/tedge`)
- run
  ```shell
  sudo /mnt/data/hmi/tedge/usr/bin/tedge_mapper --config-dir=/mnt/data/tedge c8y
  ```

**Expected behavior**
the mapper starts and works

**Screenshots**
```shell
UN65XXXXM01003541 admin@HMI-1723:~$ ls /etc/tedge
ls: /etc/tedge: No such file or directory

UN65XXXXM01003541 admin@HMI-1723:~$ sudo /mnt/data/hmi/tedge/usr/bin/tedge_mapper --config-dir=/mnt/data/tedge c8y
2022-03-30T08:00:12.33282591Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-c8y.lock"
Error: Failed to read directory: /etc/tedge/operations/c8y

# Cheating via symlinks works:
UN65XXXXM01003541 admin@HMI-1723:~$ sudo ln -s /mnt/data/tedge /etc/tedge
UN65XXXXM01003541 admin@HMI-1723:~$ sudo /mnt/data/hmi/tedge/usr/bin/tedge_mapper --config-dir=/mnt/data/tedge c8y
2022-03-30T08:04:50.20401935Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-c8y.lock"
2022-03-30T08:04:50.215492265Z  INFO init: c8y_api::http_proxy: Initialisation
2022-03-30T08:04:50.8753416Z  WARN init: rustls::check: Received a ServerHelloDone handshake message while expecting [CertificateRequest]
2022-03-30T08:04:50.970983011Z  INFO init: c8y_api::http_proxy: Initialisation done.
2022-03-30T08:04:50.972404375Z  INFO tedge_mapper::core::mapper: tedge-mapper-c8y starting
2022-03-30T08:04:50.978412839Z  INFO tedge-mapper-c8y: tedge_mapper::core::mapper: Running
```

**Environment (please complete the following information):**
 - Linux HMI-1723 4.14.78-rt47-1.0.0-ga #1 SMP PREEMPT RT Thu Dec 16 17:11:32 UTC 2021 armv7l GNU/Linux
 - thin-edge.io version custom build of commit f8d1f569

### PR DESCRIPTION
**Pull request by PradeepKiruvale**
## Proposed changes

This PR captures the code changes to use the `config-dir` option for `init` to create all the required directories and files in `Path/to/base/dir`

`tedge --init --config-dir Path/to/base/dir`
`tedge-mapper --init --config-dir Path/to/base/dir` c8y/az/collectd 
`tedge-agent --init --config-dir Path/to/base/dir`

Also, when the `mappers and agent` are started `create/read/write` config files in/from `Path/to/base/dir`
`tedge-mapper  --config-dir Path/to/base/dir` c8y/az/collectd
`tedge-agent --config-dir Path/to/base/dir`

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: crates/core/tedge_mapper/src/az/mapper.rs [hunk 1]
```diff
@@ -39,7 +42,11 @@ impl TEdgeComponent for AzureMapper {
         Ok(())
     }
 
-    async fn start(&self, tedge_config: TEdgeConfig) -> Result<(), anyhow::Error> {
+    async fn start(
+        &self,
+        tedge_config: TEdgeConfig,
+        _config_dir: &PathBuf,
```
Comment (rina23q) [inline crates/core/tedge_mapper/src/az/mapper.rs:48]: Why do we need `_config_dir` here?

**Comment by rina23q** [comment]
By the way, is it correct?
> tedge-mapper c8y/az/collectd --config-dir Path/to/base/dir
> tedge-agent --config-dir Path/to/base/dir

I think
```
tedge_mapper --config-dir Path/to/base/dir c8y/az/collectd
tedge_agent --config-dir Path/to/base/dir
```

File: crates/core/tedge_agent/src/state.rs [hunk 2]
```diff
@@ -39,7 +39,7 @@ impl StateRepository for AgentStateRepository {
     async fn store(&self, state: &State) -> Result<(), StateError> {
         let toml = toml::to_string_pretty(&state)?;
 
-        // Create `$HOME/.tedge` or `/etc/tedge` directory in case it does not exist yet
+        // Create in path given through `config-dir` or `/etc/tedge` directory in case it does not exist yet
```
Comment (albinsuresh) [inline crates/core/tedge_agent/src/state.rs:42]:
```suggestion
        // Create the directory passed in as `--config-dir` or `/etc/tedge` directory in case it does not exist yet
```

File: crates/core/tedge/src/main.rs [hunk 3]
```diff
@@ -45,12 +47,23 @@ fn main() -> anyhow::Result<()> {
     }
 }
 
-fn initialize_tedge() -> anyhow::Result<()> {
-    create_directory_with_user_group("/etc/tedge", "tedge", "tedge", 0o775)?;
+fn initialize_tedge(cfg_dir: &PathBuf) -> anyhow::Result<()> {
+    let config_dir = cfg_dir.as_path().display().to_string();
+    create_directory_with_user_group(&config_dir, "tedge", "tedge", 0o775)?;
     create_directory_with_user_group("/var/log/tedge", "tedge", "tedge", 0o775)?;
```
[the remark this answers is not in the document]
Comment (PradeepKiruvale) [reply crates/core/tedge/src/main.rs:53]: Good idea, I think we should discuss it.

File: crates/core/tedge_mapper/src/az/mapper.rs (hunk 1 above)
Comment (PradeepKiruvale) [reply crates/core/tedge_mapper/src/az/mapper.rs:48]: Because, `start` is defined in a `trait`, and it's being implemented by all mappers.  We use it or not, has to pass that parameter.

**Comment by PradeepKiruvale** [comment]
> By the way, is it correct?
> 
> > tedge-mapper c8y/az/collectd --config-dir Path/to/base/dir
> > tedge-agent --config-dir Path/to/base/dir
> 
> I think
> 
> ```
> tedge_mapper --config-dir Path/to/base/dir c8y/az/collectd
> tedge_agent --config-dir Path/to/base/dir
> ```

Yes, that's right. I have updated.

File: crates/core/tedge/src/main.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (rina23q) [reply crates/core/tedge/src/main.rs:53]: I'll create an issue after you merge this PR.

**Review by rina23q — APPROVED** [review]
