### PR TITLE
fix #3279: Create a fast path for sending `PublishMessage`s

### LINKED ISSUE #3279: c8y mapper not starting up reliably
**Describe the bug**
When ever I restart my machine or restart the c8y mapper service (`sudo systemctl restart tedge-mapper-c8y.service`) it is not really reliably starting up again. The mqtt messages on the `te/#` topics are not processed so that no messages are actually published to the `c8y/#` topic.

I've kept the mapper in this not functioning state for ~8 hours to verify if it comes back online at some point, but it does not.
About 1 out of 5 startup attempts of the service is succeeding for me. I had the feeling that with debug logging enabled for the mapper it was starting up a bit more reliable.. Maybe some race condition? I've also got 82 child devices connected right now. I'm not sure what the mapper might be doing on startup, but maybe the number of devices is triggering a race condition?

**To Reproduce**
- Restart the c8y mapper using `sudo systemctl restart tedge-mapper-c8y.service`
- verify whether mqtt messages are still sent to `c8y/#`

**Expected behavior**
Restarting the `tedge-mapper-c8y` service should not cause any issues and the mapping functionality should proceed afterwards.

**Screenshots**
-

**Environment (please complete the following information):**
|Property|Value|
|--------|-----|
|OS [incl. version]|`Debian GNU/Linux 12 (bookworm)`|
|Hardware [incl. revision]|`Raspberry Pi 4 Model B Rev 1.2`|
|System-Architecture|`Linux raspberrypi 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux`|
|thin-edge.io version|`tedge 1.3.1`|
|mosquitto version|`2.0.11`|

**Additional context**
I've got about 82 device child devices connected to my thin-edge instance.

I've attached an encrypted debug log file: [thin-edge-c8y-mapper.age.log](https://github.com/user-attachments/files/18004636/thin-edge-c8y-mapper.age.log)

### PR DESCRIPTION
**Pull request by Bravo555**
## Proposed changes

Solve the deadlock that can arise when C8yMapperActor can't complete sending MqttMessage to some other actor because that other actor can't complete the send of a `PublishMessage` to C8yMapperActor by creating a fast path to drain PublishMessage buffer ASAP.

Previously when `PublishMessage`s were a part of the main message box we could not prioritize them because we had to process messages in order;

separating out the receiver for `PublishMessage`s makes it so no other messages can block `PublishMessage`s and allows us to use select! to concurrently process them when processing other events blocks

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue

- #3279

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

About the test: added one in Robot Framework, but it has some problems: for some reasons it takes very long and it publishes a lot of messages to the cloud. Given that this test could be 100% local and would complete almost instantly as a Rust unit test, it would probably be an improvement to move it there but it's easier to add in Robot Framework for now.

### CODE REVIEW

File: crates/extensions/c8y_mapper_ext/src/actor.rs [hunk 1]
```diff
@@ -111,20 +123,27 @@ impl Actor for C8yMapperActor {
...
+                        }
+                        C8yMapperInput::FsWatchEvent(event) => {
+                            self.process_file_watch_event(event).await?;
+                        }
+                        C8yMapperInput::SyncComplete(_) => {
+                            self.process_sync_timeout().await?;
+                        }
+                    }
+                }
+                else => break
```
Comment (Bravo555) [inline crates/extensions/c8y_mapper_ext/src/actor.rs:146]: Good thing that we went over the details of `select!` usage today 😅

File: crates/extensions/c8y_mapper_ext/src/actor.rs [hunk 2]
```diff
@@ -111,20 +123,28 @@ impl Actor for C8yMapperActor {
...
-                C8yMapperInput::PublishMessage(message) => {
+        loop {
+            select! {
+                // in some tests may not be connected to the sender, so we need to ignore `None`
+                // here, but should get picked up by the main message box anyway
+                Some(message) = self.publish_messages.recv() => {
                     self.mqtt_publisher.send(message.0).await?;
                 }
+                event = self.messages.recv() => {
+                    let Some(event) = event else { break; };
```
Comment (didier-wenzek) [inline crates/extensions/c8y_mapper_ext/src/actor.rs:134]: The following seems more appropriate: i.e. let consume the published messages till the end even if there is no more input messages.

```suggestion
                Some(event) = self.messages.recv() => {
```

**Review by didier-wenzek — COMMENTED** [review]
Introducing a second receiver is a nice way to manage priority among messages, here to process first any message that is a reaction of the latest processed message.

Thank you for your perseverance, trying several fixes before finding the more appropriate one.

I will be please to see this PR merged. Just one request: can you add a system test reproducing the issue i.e. when the mapper starts with a long pending list of child device registration.

**Comment by didier-wenzek** [comment]
I confirm that:

- the [test](https://github.com/thin-edge/thin-edge.io/pull/3295/commits/55426e2068a3753530a378a34ec30f031f82023d) correctly reproduce the [issue](https://github.com/thin-edge/thin-edge.io/issues/3279), the mapper blocking on start when overwhelmed with too many child device registration messages
- this PR correctly fix the issue removing the deadlock from the c8y mapper.

File: crates/extensions/c8y_mapper_ext/src/actor.rs (hunk 2 above)
Comment (didier-wenzek) [reply crates/extensions/c8y_mapper_ext/src/actor.rs:134]: No, I'm wrong this would block the mapper on `^C`, as `self.messages.recv()` returns `None` in such a case.

**Comment by didier-wenzek** [comment]
> About the test: added one in Robot Framework, but it has some problems: for some reasons it takes very long and it publishes a lot of messages to the cloud. Given that this test could be 100% local and would complete almost instantly as a Rust unit test, it would probably be an improvement to move it there but it's easier to add in Robot Framework for now.

I'm okay with this for now.

**Review by didier-wenzek — APPROVED** [review]
Approved.

Thank you for your perseverance and the nice solution you arrived at by exploring several alternatives.

File: crates/extensions/c8y_mapper_ext/src/actor.rs [hunk 3]
```diff
@@ -111,20 +123,28 @@ impl Actor for C8yMapperActor {
...
-                C8yMapperInput::FsWatchEvent(event) => {
-                    self.process_file_watch_event(event).await?;
-                }
-                C8yMapperInput::SyncComplete(_) => {
-                    self.process_sync_timeout().await?;
-                }
-                C8yMapperInput::PublishMessage(message) => {
+        loop {
+            select! {
+                // in some tests may not be connected to the sender, so we need to ignore `None`
```
Comment (albinsuresh) [inline crates/extensions/c8y_mapper_ext/src/actor.rs:128]:
```suggestion
                // in some tests may not be connected to the sender, so we need to ignore `None`
```
What may not be connected to the sender?

**Review by albinsuresh — APPROVED** [review]
LGTM

**Review by rina23q — COMMENTED** [review]
Minor thing. 
I think the system test is more appropriate to be located under the `registration` directory as it's not a part of availability feature, rather (a lot of) child device registration. The test checks `101`, which is SmartREST child device registration message. Though it was connected to the AvailabilityActor.

So my suggestion is moving the test from `/availability` to `/registration`.

File: crates/extensions/c8y_mapper_ext/src/actor.rs (hunk 3 above)
Comment (Bravo555) [reply crates/extensions/c8y_mapper_ext/src/actor.rs]: Corrected the comment to mention the AvailabilityActor

**Review by rina23q — APPROVED** [review]
