### PR TITLE
#911 systemd init and connection reset fix 

### LINKED ISSUE #911: Issue to connect to c8y with tedge
**Describe the bug**

When we connect to C8y something goes wrong. Not sure what happens here in the mechanics of the agent and the mapper.
Maybe also two entities are trying to use the same client ID:

Here are the observations:

When we connect, we observe this message
image

(Unfortunately the return code here is 0)

In the journalctl we observe this

image

In the mosquitto log, we observe this:

image

There is also a missing check for return codes in the ci/ci_smoke_test_c8y.sh script (maybe a set -e detected this before). As as side effect with the return code of tedge connect the integration tests workflow passes, but shouldn't.

**To Reproduce**

Build upon main branch (a47fa354cddd558a59c70b8ea77546f00bae59dd)
`sudo tedge connect c8y`

**Expected behavior**
Works :)

**Screenshots**
see above

**Environment (please complete the following information):**
 - OS Debian Bullseye (11),  Raspberry Pi OS 10
 - System-Architecture: 5.10.0-11-rt-amd64
 - thin-edge.io version 0.5.3

**Additional context**
context

### PR DESCRIPTION
**Pull request by initard**
Signed-off-by: initard <solo@softwareag.com>
Signed-off-by: Rina Fujino <18257209+rina23q@users.noreply.github.com>

## Proposed changes
Closes #911 
Removing sm-c8y-mapper from init files.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
#911 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by didier-wenzek** [comment]
A better fix would be to use an unnamed session with the clear-session flag set to true.

Indeed, for JWT we don't want old tokens previously posted and if no name is provided `mqtt_channel::connect()` will generate a fresh one.

**Comment by initard** [comment]
> A better fix would be to use an unnamed session with the clear-session flag set to true.
> 
> Indeed, for JWT we don't want old tokens previously posted and if no name is provided `mqtt_channel::connect()` will generate a fresh one.

Removed all session names for mqtt and http calls

File: plugins/log_request_plugin/src/main.rs [hunk 1]
```diff
@@ -11,18 +11,13 @@ use smartrest::{
...
+/// creates an mqtt client
+pub async fn create_mqtt_client() -> Result<mqtt_channel::Connection, anyhow::Error> {
     let tedge_config = get_tedge_config()?;
     let mqtt_port = tedge_config.query(MqttPortSetting)?.into();
     let mqtt_config = mqtt_channel::Config::default()
         .with_port(mqtt_port)
-        .with_session_name(session_name)
         .with_subscriptions(mqtt_channel::TopicFilter::new_unchecked(
             C8yTopic::SmartRestResponse.as_str(),
         ));
```
Comment (didier-wenzek) [inline plugins/log_request_plugin/src/main.rs:23]: This is okay but could be improved.

* There is no need to subscribe, since no messages are expected.
* The session should be clean, since we are not using the same name from one session to another. In fact this should be implictly done by the `mqtt_channel` crate when no name is provided for the session.

**Review by didier-wenzek — APPROVED** [review]
Approved.

File: plugins/log_request_plugin/src/main.rs (hunk 1 above)
Comment (didier-wenzek) [reply plugins/log_request_plugin/src/main.rs:23]: I created a PR so it's useless to explicitly set the clean session flag when no name is provided. See https://github.com/thin-edge/thin-edge.io/pull/917

**Review by abelikt — APPROVED** [review]
Works for me :)
Fixes everything in #911

File: crates/core/tedge_mapper/src/c8y/mapper.rs [hunk 2]
```diff
@@ -16,6 +16,7 @@ use tracing::{info, info_span, Instrument};
 use super::topic::C8yTopic;
 
 const CUMULOCITY_MAPPER_NAME: &str = "tedge-mapper-c8y";
+const CUMULOCITY_MAPPER_HTTP_PROXY_NAME: &str = "tedge-mapper-c8y-jwt";
```
Comment (PradeepKiruvale) [inline crates/core/tedge_mapper/src/c8y/mapper.rs:19]: This is not used anywhere.

File: plugins/log_request_plugin/src/main.rs [hunk 3]
```diff
@@ -11,18 +11,13 @@ use smartrest::{
...
-pub async fn create_mqtt_client(
-    session_name: &str,
-) -> Result<mqtt_channel::Connection, anyhow::Error> {
+/// creates an mqtt client
+pub async fn create_mqtt_client() -> Result<mqtt_channel::Connection, anyhow::Error> {
     let tedge_config = get_tedge_config()?;
     let mqtt_port = tedge_config.query(MqttPortSetting)?.into();
     let mqtt_config = mqtt_channel::Config::default()
         .with_port(mqtt_port)
-        .with_session_name(session_name)
```
Comment (PradeepKiruvale) [inline plugins/log_request_plugin/src/main.rs:25]: Session name is not required for this MQTT client?,

File: crates/core/tedge_mapper/src/c8y/mapper.rs (hunk 2 above)
Comment (initard) [reply crates/core/tedge_mapper/src/c8y/mapper.rs]: thanks!
