### PR TITLE
fixing panic when wrong command set in template #983

### LINKED ISSUE #983: tedge_mapper c8y panics when wrong command path is provided in log file request operation
**Describe the bug**
If the `command` path is invalid, the `tedge_mapper c8y` panics after it receives a log file request operation from Cumulocity.

```
[exec]
topic = "c8y/s/ds"
on_message = "522"
command = "/usr/bin/tedge_logfile_request_plugin"
```

The problem is `unwrap()` here.
https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_mapper/src/c8y/converter.rs#L590

**To Reproduce**
1. Configure invalid `command` path in /etc/tedge/operations/c8y/c8y_LogfileRequest.
2. Run tedge_mapper c8y
3. Trigger a log file request from Cumulocity.

**Expected behavior**
No panic. No core dump.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version 0.5.3

### PR DESCRIPTION
**Pull request by initard**
## Proposed changes
- Closes #983 

- tedge-mapper was previously leaving operations hanging dead in the
      cloud if the wrong command path was set inside the template file
      in /etc/tedge/operations/<cloud>/operation_name
- this will fix handles the error, (removing the unwrap)
- it also ensures that operation status is updated to executing and
      then to failed.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: crates/core/tedge_mapper/src/c8y/converter.rs [hunk 1]
```diff
@@ -576,24 +579,35 @@ async fn validate_and_publish_software_list(
...
-async fn execute_operation(payload: &str, command: &str) -> Result<(), CumulocityMapperError> {
+async fn execute_operation(
+    payload: &str,
+    command: &str,
+    operation_name: &str,
+) -> Result<(), CumulocityMapperError> {
     let command = command.to_owned();
     let payload = payload.to_string();
 
-    let _handle = tokio::spawn(async move {
```
Comment (didier-wenzek) [inline crates/core/tedge_mapper/src/c8y/converter.rs:583]: Removing this `tokio::spawn` makes the operation blocking and will prevent the mapper to do anything till the operation is ended.

It's correct to do as done here . i.e to spawn a child process to be able to check an error on launch. But, if the process is successfully spawned, one needs to wait for the child to terminate in a `tokio::spawn` thread.

=> The `tokio::spawn` removed here must be re-introduced elsewhere.

File: crates/core/tedge_mapper/src/c8y/converter.rs [hunk 2]
```diff
@@ -576,24 +579,35 @@ async fn validate_and_publish_software_list(
...
+        .map_err(|e| CumulocityMapperError::ExecuteFailed {
+            error_message: e.to_string(),
+            command: command.to_string(),
+            operation_name: operation_name.to_string(),
+        });
 
-    Ok(())
+    match child {
+        Ok(mut child) => {
+            let _ = child.wait().await;
```
Comment (didier-wenzek) [inline crates/core/tedge_mapper/src/c8y/converter.rs:604]: This is where I would re-introduce the now missing `tokio::spawn`. __This has to be double-checked__.

```suggestion
            let _ = tokio::spawn(child.wait());
```

**Review by didier-wenzek — CHANGES_REQUESTED** [review]
The current fix introduces a bug: the mapper is blocked till an operation is fully complete.

File: crates/core/tedge_mapper/src/c8y/converter.rs (hunk 1 above)
Comment (initard) [reply crates/core/tedge_mapper/src/c8y/converter.rs:583]: Oh! Thank you, I did wonder why that was there. It seemed redundant, but now I see how important it is!

File: crates/core/tedge_mapper/src/c8y/converter.rs (hunk 2 above)
Comment (initard) [reply crates/core/tedge_mapper/src/c8y/converter.rs:604]: Yes, thank you!

**Review by didier-wenzek — APPROVED** [review]
Approved.

I manually tested that the mapper is not blocked during an operation as well as that execution errors are correctly managed.

As suggested by @PradeepKiruvale, it might be good to add an automated test checking the mapper is not blocker during an operation.
