### PR TITLE
#596 Declare supported operations

### LINKED ISSUE #596: Declaring a new supported operation for c8y
A device owner can add, list and remove the operations a device supports when connected to Cumulocity.

The point here is to notify Cumulocity of the set of supported operations, not to install and run the associated operation plugins.

AC:

* Installing a new component (like remote access) must not delete other supported_operations
* The operations supported for C8Y on a device are configured in the `/etc/tedge/operations/c8y` directory.
* Each operation is represented by an empty file named after the Cumulocity operation name (for instance `c8y_LogfileRequest`).
* On start, the c8y mapper notifies Cumulocity with a `114` message listing all the capabilities with a configuration file in `/etc/tedge/operations/c8y`.
* 
* The c8y mapper is not responsible for any operation processing.
** Notably, the plugin is in responsible for the request interpretation and execution as well as for reporting the operation progress.
** An exception is related to any request that is addressed to an operation that is not listed in  `/etc/tedge/operations/c8y`. The c8y mapper reports this operation as failed.
* The sm_c8y mapper is updated so:
** It no more reports supported operations.
** On install, the sm c8y supported operations are configured in `/etc/tedge/operations/c8y`

### PR DESCRIPTION
**Pull request by makr11st**
## Proposed changes

Allow adding new supported operations #596 

TODO:
- [x] Documentation missing 
- [x] Refactor mapper and ops 
- [ ] Add tests for mapper
- [x] Fix existing tests
- [x] ** An exception is related to any request that is addressed to an operation that is not listed in /etc/tedge/operations/c8y. The c8y mapper reports this operation as failed.
 

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
Closes #596 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: crates/core/tedge_mapper/src/mapper.rs [hunk 1]
```diff
@@ -31,12 +34,28 @@ pub(crate) fn mqtt_config(
...
+            client,
+            converter,
+            operations,
+            _flock,
+        }
+    }
+
+    pub(crate) async fn run(&mut self, cloud: &str) -> Result<(), MqttClientError> {
         info!("Running");
+        let () = self.post_operations(cloud).await?;
```
Comment (makr11st) [inline crates/core/tedge_mapper/src/mapper.rs:58]: This doesn't look like a good idea...

File: configuration/debian/tedge_agent/postinst [hunk 2]
```diff
@@ -25,6 +25,9 @@ fi
 # Create tedge-agent state directory /etc/tedge/.agent
 install -g tedge-agent -o tedge-agent -m 754 -d /etc/tedge/.agent
 
+# Create new operations file.
+install -g tedge -o tedge -m 754 -f /etc/tedge/operations/c8y/c8y_SoftwareUpdate
```
Comment (didier-wenzek) [inline configuration/debian/tedge_agent/postinst:29]: I wonder if this the responsibility of the `tedge_agent` to tell what is supported by the `c8y-sm` mapper.

File: crates/core/c8y_smartrest/src/smartrest_serializer.rs [hunk 3]
```diff
@@ -39,32 +39,33 @@ impl Default for SmartRestSetSupportedLogType {
...
 }
 
 impl<'a> SmartRestSerializer<'a> for SmartRestSetSupportedLogType {}
 
 #[derive(Debug, Deserialize, Serialize, PartialEq)]
-pub struct SmartRestSetSupportedOperations {
+pub struct SmartRestSetSupportedOperations<'a> {
     pub message_id: &'static str,
-    pub supported_operations: Vec<&'static str>,
+    pub supported_operations: Vec<&'a str>,
```
Comment (didier-wenzek) [inline crates/core/c8y_smartrest/src/smartrest_serializer.rs:52]: Why not simply a vector of `String`?

File: crates/core/c8y_smartrest/src/smartrest_serializer.rs [hunk 4]
```diff
@@ -207,13 +208,13 @@ mod tests {
...
-    #[test]
-    fn serialize_smartrest_supported_operations() {
-        let smartrest = SmartRestSetSupportedOperations::default()
-            .to_smartrest()
-            .unwrap();
-        assert_eq!(smartrest, "114,c8y_SoftwareUpdate,c8y_LogfileRequest\n");
-    }
+    // #[test]
+    // fn serialize_smartrest_supported_operations() {
+    //     let smartrest = SmartRestSetSupportedOperations::default()
```
Comment (didier-wenzek) [inline crates/core/c8y_smartrest/src/smartrest_serializer.rs:213]: I would avoid to ignore such a test even temporarily. This is just a matter of secs to replace `default` by `new` and will be great to check that parameter lifetime of the `SmartRestSetSupportedOperations` struct is not too annoying.

File: crates/core/tedge_mapper/src/az_mapper.rs [hunk 5]
```diff
@@ -30,7 +30,7 @@ impl TEdgeComponent for AzureMapper {
         let mut mapper = create_mapper(AZURE_MAPPER_NAME, &tedge_config, converter).await?;
 
         mapper
-            .run()
+            .run("az")
```
Comment (didier-wenzek) [inline crates/core/tedge_mapper/src/az_mapper.rs:33]: Why do we need a name parameter while self has already a name?

File: crates/core/tedge_mapper/src/mapper.rs (hunk 1 above)
Comment (didier-wenzek) [reply crates/core/tedge_mapper/src/mapper.rs:58]: One point is sure is that this run for any cloud while it is C8Y specific.

I would rather extend the converter.

File: crates/core/tedge_mapper/src/converter.rs [hunk 6]
```diff
@@ -21,7 +21,29 @@ pub trait Converter: Send + Sync {
...
+            }
+        }
+    }
+
+    fn try_init_messages(&self) -> Result<Vec<Message>, Self::Error> {
+        Ok(vec![])
+    }
+
+    fn init_messages(&self) -> Vec<Message> {
+        match self.try_init_messages() {
```
Comment (albinsuresh) [inline crates/core/tedge_mapper/src/converter.rs:46]:
```suggestion
        match self.wrap_error(self.try_init_messages()) {
```

File: crates/core/tedge_mapper/src/converter.rs [hunk 7]
```diff
@@ -21,7 +21,29 @@ pub trait Converter: Send + Sync {
...
+                error!("Mapping error: {}", error);
+                vec![Message::new(
+                    &self.get_mapper_config().errors_topic,
+                    error.to_string(),
+                )]
+            }
+        }
+    }
+
+    fn try_init_messages(&self) -> Result<Vec<Message>, Self::Error> {
```
Comment (albinsuresh) [inline crates/core/tedge_mapper/src/converter.rs:41]: A `Convertor` trait meant for conversion specific logic having a method like this that generates messages out of thin air looks a bit weird. Wondering if this function really belongs in this trait or rather be a part of the initialization logic of the mapper elsewhere.

File: crates/core/tedge_mapper/src/mapper.rs [hunk 8]
```diff
@@ -70,6 +70,11 @@ impl Mapper {
 
     #[instrument(skip(self), name = "messages")]
     async fn subscribe_messages(&mut self) -> Result<(), MqttClientError> {
+        let init_messages = self.converter.init_messages();
```
Comment (albinsuresh) [inline crates/core/tedge_mapper/src/mapper.rs:73]: Could these few lines sending the init messages be moved to a separate `init` function as this piece of logic doesn't have any specific connection to `subscribe_messages` logic?

File: crates/core/tedge_mapper/src/operations.rs [hunk 9]
```diff
@@ -0,0 +1,159 @@
...
+pub struct Operations {
+    dir: PathBuf,
+    operations: OperationsMap,
+}
+
+impl Default for Operations {
+    fn default() -> Self {
+        Self {
+            dir: Path::new("/etc/tedge/operations").to_path_buf(),
+            operations: HashMap::new(),
```
Comment (albinsuresh) [inline crates/core/tedge_mapper/src/operations.rs:28]: This makes this struct a centralised repository of **all** operations **across clouds**. Do we want that? Or just have the individual cloud mappers keep only their own operation mappings? Not that I see any problem with this approach. Just asking.

File: crates/core/c8y_smartrest/src/smartrest_serializer.rs [hunk 10]
```diff
@@ -39,32 +39,33 @@ impl Default for SmartRestSetSupportedLogType {
...
             message_id: "114",
-            supported_operations: vec![
-                CumulocitySupportedOperations::C8ySoftwareUpdate.into(),
-                CumulocitySupportedOperations::C8yLogFileRequest.into(),
-            ],
+            supported_operations: supported_operations.into(),
         }
     }
+
+    pub fn add_operation(&mut self, operation: &'a str) {
```
[the remark this answers is not in the document]
Comment (makr11st) [reply crates/core/c8y_smartrest/src/smartrest_serializer.rs:63]: I suppose I went a little bit ahead of myself and added it for some of the testing. I probably will remove it.

File: configuration/debian/tedge_agent/postrm [hunk 11]
```diff
@@ -24,16 +24,24 @@ purge_agent_directory() {
...
         remove_tedge_agent_user
         remove_sudoers_file
+        remove_operation_file
         purge_agent_directory
     ;;
 
     remove)
         remove_tedge_agent_user
         remove_sudoers_file
+        remove_operation_file
```
[the remark this answers is not in the document]
Comment (makr11st) [reply configuration/debian/tedge_agent/postrm:44]: Good point. I need to remove it anyway as it should not be declared in the agent.
This is a tough one to be honest.
I put it here initially as it seemed agent was the right place, but if you think about it for a moment it is the wrong place because it is actually not agent but rather sm-mapper who adds support for this operation...

File: crates/core/c8y_smartrest/src/smartrest_serializer.rs (hunk 3 above)
Comment (makr11st) [reply crates/core/c8y_smartrest/src/smartrest_serializer.rs:52]: I wanted to keep the code fell the same across all the structs in this file where pretty much everywhere are `'static str`

File: crates/core/tedge_mapper/src/mapper.rs [hunk 12]
```diff
@@ -70,6 +70,11 @@ impl Mapper {
...
+        for init_message in init_messages.into_iter() {
+            self.client.publish(init_message).await?
+        }
```
Comment (PradeepKiruvale) [inline crates/core/tedge_mapper/src/mapper.rs:76]: Will these init messages be read from the operation configuration file?

File: crates/core/tedge_mapper/src/operations.rs [hunk 13]
```diff
@@ -0,0 +1,263 @@
...
+
+use crate::error::OperationsError;
+
+/// Operations are derived by reading files subdirectories per cloud /etc/tedge/operations directory
+/// Each operation is a file name in one of the subdirectories
+/// The file name is the operation name
+
+type Cloud = String;
+type OperationName = String;
+type Operation = HashMap<OperationName, PathBuf>;
```
Comment (PradeepKiruvale) [inline crates/core/tedge_mapper/src/operations.rs:15]: Would be better if this is postfixed with `map` for more readability.

File: crates/core/tedge_mapper/src/operations.rs [hunk 14]
```diff
@@ -0,0 +1,263 @@
...
+    }
+
+    pub fn try_new(dir: impl AsRef<Path>) -> Result<Self, OperationsError> {
+        let operations = get_operations(dir.as_ref())?;
+
+        Ok(Self {
+            dir: dir.as_ref().to_path_buf(),
+            operations,
+        })
+    }
```
Comment (PradeepKiruvale) [inline crates/core/tedge_mapper/src/operations.rs:49]: Didn't get why do we need two new functions here?

File: crates/core/tedge_mapper/src/converter.rs (hunk 7 above)
Comment (didier-wenzek) [reply crates/core/tedge_mapper/src/converter.rs:41]: Maybe the name `Converter` is misleading, but this trait responsibilities make sense. These are related to the messages to be sent to a given cloud. To translate a measurements, create a child device ... or declare that an operation is supported. The mapper main itself is then responsible of the transmission of these messages and can be cloud independent.

File: docs/src/SUMMARY.md [hunk 15]
```diff
@@ -27,6 +28,7 @@
     - [How to connect an external device?](./howto-guides/013_connect_external_device.md)
     - [How to access the logs on the device?](./howto-guides/014_thin_edge_logs.md)
     - [How to install thin-edge.io on any Linux OS (no deb support)?](./howto-guides/015_installation_without_deb_support.md)
+    - [How to use Supported Operations API?](./howto-guides/016_supported_operations.md) ]
```
Comment (didier-wenzek) [inline docs/src/SUMMARY.md:31]: Warning: This file is for now empty.

File: docs/src/tutorials/supported_operations.md [hunk 16]
```diff
@@ -0,0 +1,98 @@
...
+* Software Update Log Upload
+* Restart
+
+The list is growing as we support more operations, but is not exhaustive and we encourage you to contribute to the list.
+
+## How to use Supported Operations
+
+### Listing current operations
+
+You can obtain current list of supported operations by running listing content of `/etc/tedge/operations` directory.
```
Comment (didier-wenzek) [inline docs/src/tutorials/supported_operations.md:38]:
```suggestion
You can obtain the current list of supported operations by listing the content of the `/etc/tedge/operations` directory.
```

File: crates/core/tedge_mapper/src/sm_c8y_mapper/tests.rs [hunk 17]
```diff
@@ -48,11 +48,7 @@ async fn mapper_publishes_a_supported_operation_and_a_pending_operations_onto_c8
     mqtt_tests::assert_received(
         &mut messages,
         TEST_TIMEOUT_MS,
-        vec![
-            "114,c8y_SoftwareUpdate,c8y_LogfileRequest\n",
-            "118,software-management\n",
-            "500\n",
-        ],
+        vec!["118,software-management\n", "500\n"],
```
Comment (didier-wenzek) [inline crates/core/tedge_mapper/src/sm_c8y_mapper/tests.rs:51]: This is okay for now but this highlights something that needs to be clarified. This `118` message is related to the protocol of the `c8y_LogfileRequest` operation. This make senses because the `c8y_mapper` is no more responsible of the operation declaration but only of the implementation of some of them. But this is surprising.

File: crates/core/tedge_mapper/src/operations.rs (hunk 9 above)
Comment (didier-wenzek) [reply crates/core/tedge_mapper/src/operations.rs:28]: Is this default useful? I expect the mapper to call `Operations::try_new()` with the appropriate directory.

File: crates/core/tedge_mapper/src/operations.rs [hunk 18]
```diff
@@ -0,0 +1,263 @@
...
+    fn default() -> Self {
+        Self {
+            dir: Path::new("/etc/tedge/operations").to_path_buf(),
+            operations: HashMap::new(),
+        }
+    }
+}
+
+impl Operations {
+    pub fn new(dir: impl AsRef<Path>) -> Self {
```
Comment (didier-wenzek) [inline crates/core/tedge_mapper/src/operations.rs:34]: I would remove this `new()` function as well as the `Default` implementation to keep only the `Operations::try_new()` function.

**Review by didier-wenzek — COMMENTED** [review]
The design is in place, but many small points still need to be fixed.

File: crates/core/tedge_mapper/src/mapper.rs (hunk 12 above)
Comment (makr11st) [reply crates/core/tedge_mapper/src/mapper.rs:76]: Not the messages, but the content of them (it) will be read from operations directory.

File: crates/core/tedge_mapper/src/operations.rs (hunk 14 above)
Comment (makr11st) [reply crates/core/tedge_mapper/src/operations.rs:32]: We don't, we use `try_new`.

File: docs/src/tutorials/supported_operations.md [hunk 19]
```diff
@@ -0,0 +1,98 @@
...
+IoT devices often do more than just send data to the cloud. They also do things like:
+
+* receive triggers from the operator
+* reboot on demand
+* install or remove software
+
+These are all operations that are supported by Cumulocity IoT and other cloud providers.
+In thin-edge.io we support these operations by writing a plugin that implements the
+[`Operation`](https://cumulocity.com/guides/reference/operation) interface and registering it with the
+thin-edge.io Supported Operations API.
```
Comment (didier-wenzek) [inline docs/src/tutorials/supported_operations.md:16]: This introduction can be improved. Notably, it seems better to link the Cumulocity operation doc to Cumulocity  rather than to thin-edge. By the way, the link is broken.

```suggestion
These operations that are supported by [Cumulocity IoT](https://cumulocity.com/api/10.11.0/#section/Device-management-library) and other cloud providers. On thin-edge.io the support for one such operation can be added using the thin-edge.io Supported Operations API.
```

File: docs/src/tutorials/supported_operations.md [hunk 20]
```diff
@@ -0,0 +1,98 @@
...
+
+### thin-edge.io Supported Operations API
+
+The Supported Operations utilises file system to add and remove operations. Special file placed in `/etc/tedge/operations` directory will indicate that the operation is supported.
```
Comment (didier-wenzek) [inline docs/src/tutorials/supported_operations.md:20]:
```suggestion
The Supported Operations utilises the file system to add and remove operations. A special file placed in `/etc/tedge/operations` directory will indicate that an operation is supported.
```

File: docs/src/tutorials/supported_operations.md [hunk 21]
```diff
@@ -0,0 +1,98 @@
...
+The specification for the operation files is described in thin-edge.io specifications repository[src/supported-operations/README.md](https://github.com/thin-edge/thin-edge.io-specs/blob/a99a8cbf78a4c4c9637fb1794797cb2fb468a0f4/src/supported-operations/README.md)
+
+## thin-edge.io List of Supported Operations
+
+thin-edge.io comes with some operations that are supported `natively` by thin-edge.io.
+Following operations are supported:
```
Comment (didier-wenzek) [inline docs/src/tutorials/supported_operations.md:26]:
```suggestion
thin-edge.io supports natively the following operations:
```

**Review by didier-wenzek — COMMENTED** [review]
The feature is in place. However there are still many small details to fix.

**Review by didier-wenzek — APPROVED** [review]
Approved.
