### PR TITLE
#624 Update dependencies and error handlers

### LINKED ISSUE #624: `rustls` 0.19 -> 0.20 has breaking changes to API which prevent code compiling
We are using rustls 0.19 to extract explicit webpki::Error in tedge upload subcommand to help the user get better information about what is failing in the connection.
rustls 0.20 removed the API in Error to expose those error:

* Breaking API change: the WebPkiError variant of rustls::Error now includes which operation failed. 

AC:

* Update rustls to 0.20 with keeping webpki::Error.

### PR DESCRIPTION
**Pull request by makr11st**
## Proposed changes

Updated dependencies on `rustls` crates and fixed error handlers due to new errors structures in latest `hyper`.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
Closes #624 

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: crates/core/tedge/src/cli/certificate/error.rs [hunk 1]
```diff
@@ -75,7 +75,7 @@ pub enum CertError {
     UserSwitchError(#[from] UserSwitchError),
 
     #[error("HTTP Connection Problem: {msg} \nHint: {hint}")]
-    WebpkiValidation { hint: String, msg: String },
+    CertificateValidation { hint: String, msg: String },
```
Comment (albinsuresh) [inline crates/core/tedge/src/cli/certificate/error.rs:78]:
```suggestion
    CertificateValidationFailure { hint: String, msg: String },
```

**Review by albinsuresh — APPROVED** [review]
