### PR TITLE
#882 agent start up failures

### LINKED ISSUE #882: tedge_agent fails to start when there is no sm-plugins directory
**Describe the bug**
When there is no `sm-plugins` directory in `/etc/tedge` the `tedge_agent` fails to start.
The error message is not verbose enough to say what is exactly missing.

**To Reproduce**
To reproduce, remove the `sm-plugins` directory if it already exists in `/etc/tedge` directory.
Then start the tedge_agent as `sudo tedge_agent`

**Expected behavior**
The error message must say what exactly is missing.
For example: Error: I/O error: "`/etc/tedge/sm-plugins` No such file or directory (os error 2)"

**Screenshots**
2022-02-16T05:52:34.034+00:00  INFO tedge_agent::agent: tedge_agent starting
2022-02-16T05:52:34.034+00:00  INFO sm-agent: tedge_agent::agent: Starting tedge agent
Error: I/O error: "No such file or directory (os error 2)"

**Environment (please complete the following information):**
 - OS [ubuntu]
 - Hardware [x64]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io v0.5.2

**Additional context**

AC:
- tedge_agent shouldn`t fail if sm-plugins directory is not there.
- Only print information that there are no sm-plugins installed nor loading
- tedge_agent should point to tedge_agent --init if operations or .agent folder is missing and fail.

### PR DESCRIPTION
**Pull request by initard**
## Proposed changes

- Closes #882

Error handling for tedge agent and mapper, when there is no directory on startup (.agent, operations, sm-plugins)

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
#882

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by makr11st — COMMENTED** [review]
Clippy, remove unused

File: crates/core/tedge_agent/src/state.rs [hunk 1]
```diff
@@ -28,7 +29,10 @@ impl StateRepository for AgentStateRepository {
         match fs::read(&self.state_repo_path).await {
             Ok(bytes) => Ok(toml::from_slice::<State>(bytes.as_slice())?),
 
-            Err(err) => Err(StateError::FromIo(err)),
+            Err(err) => {
+                error!("Error reading: {:?}", &self.state_repo_path);
+                return Err(StateError::FromIo(err));
```
Comment (rina23q) [inline crates/core/tedge_agent/src/state.rs:34]: `return` is unnecessary.

```suggestion
                Err(StateError::FromIo(err))
```

File: crates/core/c8y_smartrest/src/operations.rs [hunk 2]
```diff
@@ -98,12 +98,17 @@ fn get_operations(dir: impl AsRef<Path>, cloud_name: &str) -> Result<Operations,
...
+        Ok(entry) => entry
+            .map(|entry| entry.map(|e| e.path()))
+            .collect::<Result<Vec<PathBuf>, _>>()?
+            .into_iter()
+            .filter(|path| path.is_file())
+            .collect::<Vec<PathBuf>>(),
+        Err(_err) => {
+            return Err(OperationsError::InvalidOperationName(PathBuf::from(&path)));
+        }
+    };
```
Comment (rina23q) [inline crates/core/c8y_smartrest/src/operations.rs:111]: It's up to the preference, but you can also write like this without using `match`.

```suggestion
    let dir_entries = fs::read_dir(&path)
        .map_err(|_| OperationsError::InvalidOperationName(PathBuf::from(&path)))?
        .map(|entry| entry.map(|e| e.path()))
        .collect::<Result<Vec<PathBuf>, _>>()?
        .into_iter()
        .filter(|path| path.is_file())
        .collect::<Vec<PathBuf>>();
```

File: crates/core/plugin_sm/src/plugin_manager.rs [hunk 3]
```diff
@@ -1,4 +1,4 @@
-use crate::plugin::{Plugin, LIST};
+use crate::plugin::{self, Plugin, LIST};
```
Comment (rina23q) [inline crates/core/plugin_sm/src/plugin_manager.rs:1]: Remove `self` as the warning.

File: crates/core/plugin_sm/src/plugin_manager.rs [hunk 4]
```diff
@@ -96,7 +96,10 @@ impl ExternalPlugins {
             default_plugin_type: default_plugin_type.clone(),
             sudo,
         };
-        let () = plugins.load()?;
+        if let Err(e) = plugins.load() {
+            warn!("{:?}: {:?}", e.kind(), &plugins.plugin_dir);
+            return Ok(plugins);
```
Comment (rina23q) [inline crates/core/plugin_sm/src/plugin_manager.rs:101]: I think this one should stay as an error. This is true that the function fails to open the plugins because there is nothing.

Rather, we should change the logic of the line 204, not to return the error, and just to log `warn`.

```
        let plugins = Arc::new(Mutex::new(ExternalPlugins::open(
            self.config.sm_home.join("sm-plugins"),
            get_default_plugin(&self.config.config_location)?,
            Some("sudo".into()),
        )?));
```

Comment (initard) [reply crates/core/plugin_sm/src/plugin_manager.rs:101]: Not sure I follow, let's discuss this tomorrow

File: crates/core/c8y_smartrest/src/operations.rs [hunk 5]
```diff
@@ -98,7 +98,8 @@ fn get_operations(dir: impl AsRef<Path>, cloud_name: &str) -> Result<Operations,
     let mut operations = Operations::default();
 
     let path = dir.as_ref().join(&cloud_name);
-    let dir_entries = fs::read_dir(&path)?
+    let dir_entries = fs::read_dir(&path)
+        .map_err(|_| OperationsError::InvalidOperationName(PathBuf::from(&path)))?
```
Comment (albinsuresh) [inline crates/core/c8y_smartrest/src/operations.rs:102]: That wild card match for all errors from `read_dir` being mapped to `OperationsError::InvalidOperationName` might lead to some misleading errors when the dir doesn't even exist. The error message of `InvalidOperationName` is "Cannot extract the operation name from the path". That doesn't sound right when the file itself is missing or when the mapper doesn't have the rights to read that file.

Either we need a more generic `OperationsError` enum with a generic message or the mapping should be more specific rather than `|_|`. I understand that `std::io::Error` is not very handy for such specific mappings. In that case, the former might be the way out.

File: crates/core/plugin_sm/src/plugin_manager.rs [hunk 6]
```diff
@@ -96,7 +96,10 @@ impl ExternalPlugins {
             default_plugin_type: default_plugin_type.clone(),
             sudo,
         };
-        let () = plugins.load()?;
+        if let Err(e) = plugins.load() {
+            warn!("{:?}: {:?}", e.kind(), &plugins.plugin_dir);
```
Comment (albinsuresh) [inline crates/core/plugin_sm/src/plugin_manager.rs:100]: That warning log statement should give more context, something like:
```suggestion
            warn!("Reading the plugins directory: failed with : {:?}: {:?}", &plugins.plugin_dir, e.kind());
```

File: crates/core/plugin_sm/src/plugin_manager.rs (hunk 4 above)
Comment (albinsuresh) [reply crates/core/plugin_sm/src/plugin_manager.rs:101]: I don't really consider the plugins directory being empty as an `Error`. So, I'm fine with a log. But if the plugins directory itself, or the plugins in that directory aren't readable, that could be considered an error.

File: crates/core/plugin_sm/src/plugin_manager.rs [hunk 7]
```diff
@@ -96,7 +96,10 @@ impl ExternalPlugins {
             default_plugin_type: default_plugin_type.clone(),
             sudo,
         };
-        let () = plugins.load()?;
+        if let Err(e) = plugins.load() {
```
Comment (albinsuresh) [inline crates/core/plugin_sm/src/plugin_manager.rs:99]: Can't this logic of handling empty plugins directory be unit tested?

File: crates/core/c8y_smartrest/src/error.rs [hunk 8]
```diff
@@ -1,5 +1,5 @@
 use agent_interface::SoftwareUpdateResponse;
-use std::path::PathBuf;
+use std::path::{Path, PathBuf};
```
Comment (rina23q) [inline crates/core/c8y_smartrest/src/error.rs:2]: Unused import marked by clippy.

```suggestion
use std::path::PathBuf;
```

**Comment by rina23q** [comment]
Can you do
- Remove unused import
- Fix the commit messages
Then I will approve

**Review by rina23q — APPROVED** [review]
I approve, but please choose either 

1. Use squash and merge
2. Fix the two commits on the PR to have different commit messages or merge into one, then use merge pull request.
